### ISSUE TITLE
Interesting

### ISSUE THREAD

**Issue by Peekmo** [manastech/atom-crystal-tools#1]
Hello !

I just discoverd Crystal programming language, and I'm very intested in.
I love atom editor, and I already developed a plugin for it (https://github.com/Peekmo/atom-autocomplete-php) and I would like to know if this plugin has the goal to provide some autocomplete ? If not, is there some reflection process available around crystal to be able to have the matadata of our code to be able to build simply an autocomplete provider ?

Regards,
Peekmo

**Comment by bcardiff** [comment]
Hi @Peekmo . Thanks for the interest.

Right now this plugin uses crystal:tool-impl branch. The reflection is done using the compilation result without generating the binary files. Since crystal is bootstrapped it's "easy" to code that logic.

There are some basic metadata in runtime available but not much. But, since the result of the compiler is just a binary, I would not think the runtime metadata like in Ruby is the way to go.

Regarding an autocomplete, it would be nice but is not in goal right now. The main blocker issue is the parser. If ‸ is the cursor location, building the following source will not compile. And without the compilation/type inference is hard to know that p is of type Foo and then give accurate autocomplete information.

``` crystal
p = Foo.new
p.‸
```

**Comment by Peekmo** [comment]
Thank you for your reply.

In fact, you're right for the runtime metadata.
Perhaps there's something to do with the parser to ignore fatal errors in the searched file ? I don't really know how hard it is, I just started to fork the crystal repository and to try to read the code. (I'm really interested on this kind of work^^)

Peekmo

**Comment by bcardiff** [comment]
Yes, the parser should try to recover from an invalid syntax in order to go this way. This should be discussed in crystal itself. This package will be just a wrapper to crystal built in tools :-)

And, regarding metadata in case you want to read a recent discussion https://groups.google.com/d/msgid/crystal-lang/CA%2BdJ3wR%3DXXZkXHV53kHWc%3DMw7S6Z_eHGRRK9NkWSvDS%3Dt6n6NQ%40mail.gmail.com?utm_medium=email&utm_source=footer

I will close this, but I hope to see you in main crystal repo/mailing list for contribs or feedback :smile_cat:

**Comment by Peekmo** [comment]
Thank you for your answers,
Peekmo
