### ISSUE TITLE
/bin/sh: crystal: command not found OSx

### ISSUE THREAD

**Issue by stephan-nordnes-eriksen** [manastech/atom-crystal-tools#4]
I have added crystal to my path variable, but I still get `/bin/sh: crystal: command not found` when using this plugin in atom.

I added crystal to my path by the following method:

1:

```
sudo nano /etc/paths
```

2: 
Add `/path/to/my/crystal/bin`

3:
Restart Atom.

This did not resolve my issue. I can verify that crystal is in my path by `echo $PATH`, but for some reason atom-crystal-tools does not find it :( What can I do to resolve this?

(I have also tried system reboot, with no luck)

**Comment by bcardiff** [comment]
It should be detected if it is in your path. But as a workaround you can set the real path in the package settings.

![screen shot 2015-10-06 at 11 53 45 am](https://cloud.githubusercontent.com/assets/459923/10312303/122a11ac-6c21-11e5-91ae-11b532047b4d.png)

The default is just `crystal` and that's why it should work.

**Comment by stephan-nordnes-eriksen** [comment]
When setting it manually, it worked. 

If I leave it blank it does not work. Weird

**Comment by bcardiff** [comment]
@r00takaspin glad you figured it out. On some environments I also noticed that atom needs to be started from the console/terminal in order to have crystal in it's path.
